# Builds src/lyrics.local.js from the lyrics file named in job.json ("lyrics") ("mm:ss text" per line).
# Each whole-second timestamp is snapped to the strongest vocal onset inside its one-second window,
# then quantized to the 16th-note grid of job.json's beat. Usage: python3 tools/make_lyrics.py
import librosa, numpy as np, json, re, os
root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
job = json.load(open(os.path.join(root, 'job.json')))
L = []
for ln in open(os.path.join(root, job['lyrics']), encoding='utf-8-sig'):
    m = re.match(r'(\d+):(\d+)\s+(.*)', ln.strip())
    if m: L.append([int(m[1]) * 60 + int(m[2]), m[3].strip().replace('ﬁ', 'fi').replace('ﬂ', 'fl')])
y, sr = librosa.load(os.path.join(root, job['audio']), sr=22050, mono=False)
mid, side = (y[0] + y[1]) / 2, (y[0] - y[1]) / 2
hop = 256; S = np.abs(librosa.stft(mid, n_fft=2048, hop_length=hop)); f = librosa.fft_frequencies(sr=sr, n_fft=2048)
Hm, _ = librosa.decompose.hpss(S, margin=(3, 1)); Ss = np.abs(librosa.stft(side, n_fft=2048, hop_length=hop))
b = (f > 300) & (f < 3000); v = np.maximum(0, Hm[b].sum(0) - .7 * Ss[b].sum(0)); v = np.log1p(v / np.percentile(v, 50))
on = np.convolve(np.maximum(0, np.diff(v, prepend=v[0])), np.ones(3) / 3, 'same'); t = np.arange(len(on)) * hop / sr
P, O = job['beat'], job['offset']; q = P / 4
out = []
for s, txt in L:
    w = (t >= s - .25) & (t < s + 1.0); ts = t[w][np.argmax(on[w])]
    out.append([round(O + round((ts - O) / q) * q, 3), 0, txt])
for i in range(1, len(out)):
    if out[i][0] <= out[i - 1][0] + .3: out[i][0] = round(out[i - 1][0] + P, 3)
for i in range(len(out)):
    out[i][1] = min(out[i + 1][0] if i + 1 < len(out) else out[i][0] + 3.2, round(out[i][0] + 5.5, 3))
open(os.path.join(root, 'src/lyrics.local.js'), 'w').write(
    '// Generated by tools/make_lyrics.py from the job.json lyrics file. Do not edit.\nwindow.LY_LOCAL = [\n' +
    ',\n'.join('  ' + json.dumps(x, ensure_ascii=False) for x in out) + '\n];\n')
print(len(out), 'lines')
