// hooks.js: the two title phrases of the song and when they are sung, for the big recurring title moments.
// (All lyric lines are in LY, generated by tools/make_lyrics.py; these are the moments inside them to make huge.)
// [start, end, text]
const HOOKS = [
  [73.4, 74.9, 'Khuôn Mặt Đáng Thương'],
  [83.5, 84.94, 'Khuôn Mặt Đáng Thương'],
  [84.94, 86.3, 'cánh hoa úa tàn'],
  [134.0, 135.5, 'Khuôn Mặt Đáng Thương'],
  [144.1, 146.2, 'Khuôn Mặt Đáng Thương'],
  [146.2, 151.0, 'cánh hoa úa tàn'],
  [151.0, 155.0, 'cánh hoa úa tàn'],
  [155.0, 159.0, 'cánh hoa úa tàn'],
  [159.0, 166.5, 'cánh hoa úa tàn'],
  [230.4, 236.2, 'cánh hoa úa tàn'],
  [237.4, 241.0, 'Khuôn Mặt Đáng Thương'],
];
// Where the voice is singing (from the transcript), for faces that sing / breathe: [start, end]
const VOCAL = [[16, 33], [34, 60.5], [61, 86.2], [86.2, 101.5], [101.5, 126.5], [128, 146.5], [147.8, 166.5], [179.3, 212], [213, 226], [229.3, 241.5]];
