// Writes the generated model as JSON (for the renderer/checker) and as an LDraw MPD with steps and sub-models.
import fs from 'node:fs';
const fmt = v => (Math.round(v * 1000) / 1000).toString();
const line = p => `1 ${p.color} ${p.pos.map(fmt).join(' ')} ${p.R.map(fmt).join(' ')} ${p.part}.dat`;
const slug = s => s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/đ/g, 'd').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') + '.ldr';

// Split steps with too many parts into several steps (bottom layers first, then back to front).
function splitSteps(m, max = 20) {
  const steps = [], remap = new Map();
  for (const s of m.steps) {
    const ps = m.parts.filter(p => p.step === s.i);
    if (ps.length <= max) { const n = { ...s, i: steps.length }; steps.push(n); ps.forEach(p => remap.set(p, n.i)); continue; }
    ps.sort((a, b) => b.pos[1] - a.pos[1] || a.pos[2] - b.pos[2] || a.pos[0] - b.pos[0]);
    const chunks = Math.ceil(ps.length / max), size = Math.ceil(ps.length / chunks);
    for (let c = 0; c < chunks; c++) {
      const n = { ...s, i: steps.length, part: `${c + 1}/${chunks}` };
      if (c > 0) { delete n.note; delete n.attach; }
      if (c < chunks - 1) delete n.attach;
      steps.push(n);
      ps.slice(c * size, (c + 1) * size).forEach(p => remap.set(p, n.i));
    }
  }
  for (const p of m.parts) p.step = remap.get(p);
  m.steps = steps;
}

export function writeOutputs(m, OUT, mpdName = 'model') {
  fs.mkdirSync(OUT, { recursive: true });
  splitSteps(m);
  const parts = m.parts.map(({ cells, ...p }) => p);
  const model = { name: m.name, bags: m.bagTitles, steps: m.steps, parts };
  fs.writeFileSync(OUT + 'model.json', JSON.stringify(model));

  // MPD: main model + one file per sub-model; sub-models are built in world coordinates and placed at identity
  const subs = [...new Set(parts.filter(p => p.sub).map(p => p.sub))];
  const files = [];
  const head = (name, title) => [`0 FILE ${name}`, `0 ${title}`, `0 Name: ${name}`, '0 Author: Generated by task003/model (Claude Code)', '0 !LICENSE Licensed under CC BY 4.0', ''];
  const body = (filter) => {
    const out = [];
    for (const s of m.steps) {
      const ps = parts.filter(p => p.step === s.i && filter(p));
      const attach = s.attach && filter({ sub: null }) && !filter.isSub ? [`1 16 0 0 0 1 0 0 0 1 0 0 0 1 ${slug(s.attach)}`] : [];
      if (!ps.length && !attach.length) continue;
      if (s.title) out.push(`0 // ${s.title}`);
      out.push(...ps.map(line), ...attach, '0 STEP');
    }
    return out;
  };
  const main = head(mpdName + '.ldr', m.name);
  main.push(...body(p => !p.sub));
  files.push(main.join('\n'), '0 NOFILE');
  for (const s of subs) {
    const f = p => p.sub === s; f.isSub = true;
    files.push([...head(slug(s), s), ...body(f)].join('\n'), '0 NOFILE');
  }
  fs.writeFileSync(OUT + mpdName + '.mpd', files.join('\n') + '\n');
  console.log(`model: ${parts.length} parts, ${m.steps.length} steps, sub-models: ${subs.join(', ') || 'none'}`);
}
