# Builds src/lyrics.local.js from source/lyrics.local.txt (the song's lyrics, one line per line, supplied by the user;
# kept out of the repo). This file holds only the timing: which lyric line (1-based index) is sung when, worked out
# from the machine transcript's timestamps, the 95 BPM bar grid and vocal onsets. Usage: python3 tools/make_lyrics.py
import os, json
root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
L = [l.strip() for l in open(os.path.join(root, 'source/lyrics.local.txt'), encoding='utf8') if l.strip()]
B, O = 60 / 95, 0.30987
bar = lambda k: O + k * 4 * B
T = []                                   # (start, line index)
# intro lines 1-4 are an inscription on the scroll (not sung in sync); shown by the intro scene, not here
T += [(22.0, 5), (27.8, 6), (31.0, 7)]                                      # intro, sung softly
V1 = [(34.4, 8), (38.6, 9), (41.4, 10), (45.3, 11), (49.5, 12), (51.7, 13), (54.6, 14), (59.4, 15), (62.6, 16)]
T += V1
CH = lambda b0: [(bar(b0 + k) - 2 * B, 17 + k) for k in range(8)]          # chorus: one line a bar, 2-beat pickup
T += CH(26) + [(bar(34) - 2 * B, 25)]
T += [(86.3, 26), (88.3, 27), (90.0, 28), (93.2, 29), (95.8, 30), (98.3, 31), (100.8, 32), (103.2, 33)]   # rap
T += [(t + 60.63, i) for t, i in V1 if i >= 11]                              # the verse ending, sung again
T += CH(50)
T += [(146.2, 34), (151.0, 35), (155.0, 36), (159.0, 37), (177.9, 38)]      # cánh hoa úa tàn ×4, nah woh
T += [(bar(74) - 2 * B + k * 2 * 4 * B, 39 + k) for k in range(8)]         # bridge: 8 lines, two bars each
T += [(230.4, 34), (236.4, 20)]                                              # outro fragments (…khuôn mặt đáng thương)
T.sort()
out = []
for n, (t, i) in enumerate(T):
    nxt = T[n + 1][0] if n + 1 < len(T) else t + 4.5
    txt = L[i - 1]
    if n == len(T) - 1: txt = 'khuôn mặt đáng thương'          # the last fragment is only the end of line 20
    out.append([round(t, 3), round(min(nxt, t + 7.5), 3), txt])
open(os.path.join(root, 'src/lyrics.local.js'), 'w').write('// Generated by tools/make_lyrics.py. Do not edit.\nwindow.LY_LOCAL = [\n' +
    ',\n'.join('  ' + json.dumps(x, ensure_ascii=False) for x in out) + '\n];\nwindow.LY_INTRO = ' + json.dumps(L[:4], ensure_ascii=False) + ';\n')
print(len(out), 'timed lines')
