// lyrics.js: [start, end, text]. The song's lyrics are kept out of the repository: put them in src/lyrics.local.js
// (window.LY_LOCAL, gitignored), generated by `python3 tools/make_lyrics.py` from the lyrics file named in job.json. Without it the video renders with no lyrics.
const LY = window.LY_LOCAL || [];
